### ISSUE TITLE
Pypi Package

### ISSUE THREAD

**Issue by frankV** [Pushwoosh/pushwoosh-python-lib#3]
Would really appreciate being able to install this from pip. I think a resource like this should be available on pypi anyway.

For developers finding this a problem, you can install from the repository:
`pip install git+git://github.com/Pushwoosh/pushwoosh-python-lib.git`

**Comment by ikeeip** [comment]
It's done. Enjoy! Here is the link: https://pypi.python.org/pypi/pypushwoosh
