### ISSUE TITLE
New PyPI release - 0.2.2

### ISSUE THREAD

**Issue by mdawid92** [Pushwoosh/pushwoosh-python-lib#8]
Can we have new release on PyPI (with last pull request)? Thanks!

**Comment by muffl0n** [comment]
Stumbled upon the fact that Version 0.2.1 does not use requests and therefore does not use the configured proxy.
Would love to see a new version getting released! Maybe even 0.3 to reflect this big change.

**Comment by ikeeip** [comment]
Yeah, @muffl0n it will be 0.3-ever release =) @mdawid92, I will fix some broken integration tests and release new version, asap.

**Comment by ikeeip** [comment]
Done. Enjoy!

**Comment by muffl0n** [comment]
Awesome! Thank you!
